name: Release
on:
  push:
    branches:
      - master
      - beta
      - canary
      - dev
      # - add more here as needed.
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ã€€Checkout
        uses: actions/checkout@v2

      # no yarn here, heh
      # - name: ğŸš§ã€€Install
      #   run: yarn install
      # - name: ğŸ“¦ã€€Build
      #   run: yarn build
      #npm version:
      - name: ğŸš§ã€€Install
        run: npm install

      #use this if you want to build every commit to github.
      # - name: ğŸ“¦ã€€Build
      #   run: npm publish

      # for some reason this does work so i just wont use it lol...
      # - name: ğŸ”‘ã€€Generate Token
      #   uses: wow-actions/use-app-token@v1
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}
      #     env_name: bot_token

      # - name: ğŸ“¦ã€€Release
      #   uses: wow-actions/release-github-action@v1
      #   with:
      #     GITHUB_TOKEN: ${{ env.bot_token }}
      #     GIT_COMMITTER_NAME: wow-actions-bot
      #     GIT_COMMITTER_EMAIL: wow-actions-bot@users.noreply.github.com
